# This is a basic workflow to help you get started with Actions

name: WinGet Test URLs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run myScript.ps1
        run: pwsh -File ./myScript.ps1
          
      - name: Save wingetHttpCodes.txt
        uses: actions/upload-artifact@v2
        with:
          name: wingetHttpCodes
          path: wingetHttpCodes.txt
